prometheus:
  image: prom/prometheus:latest
  container_name: monitoring_prometheus
  restart: unless-stopped
  volumes:
  - ./data/prometheus/config:/etc/prometheus/
  - ./data/prometheus/data:/prometheus
  command:
  - '--config.file=/etc/prometheus/prometheus.yml'
  - '--storage.tsdb.path=/prometheus'
  expose:
  - 9090
  ports:
  - 9090:9090

pushgateway:
  image: prom/pushgateway
  container_name: pushgateway
  restart: unless-stopped
  expose:
  - 9091
  ports:
  - "9091:9091"
  command: --web.enable-admin-api

grafana:
  image: grafana/grafana:latest
  container_name: monitoring_grafana
  restart: unless-stopped
  ports:
  - 3000:3000
  expose:
  - 3000
  links:
  - prometheus:prometheus
  volumes:
  - ./data/grafana:/var/lib/grafana
  environment:
  - GF_SECURITY_ADMIN_PASSWORD=admin1234
  - GF_USERS_ALLOW_SIGN_UP=false
  - GF_SERVER_DOMAIN=localhost
  - GF_SMTP_ENABLED=false

kafka-exporter:
  image: danielqsj/kafka-exporter
  hostname: kafka-exporter
  container_name: kafka-exporter
  restart: unless-stopped
  ports:
  - 9308:9308
  expose:
  - 9308
  command: --kafka.server=vb0630.halxg.cloudera.com:9092 --kafka.server=vb0632.halxg.cloudera.com:9092 --kafka.server=vb0634.halxg.cloudera.com:9092
